const USER_TASK = {
  RESET: "USER_TASK_RESET",

  //USER TASK LIST
  REQUEST_USER_TASKS: "REQUEST_USER_TASKS",
  RESPONSE_USER_TASKS: "RESPONSE_USER_TASKS",
  RESPONSE_NOTIFICATIONS: "RESPONSE_NOTIFICATIONS",
  USER_TASKS_LOADING: "USER_TASKS_LOADING",
  ERROR_USER_TASKS: "ERROR_USER_TASKS",

  //COMPLETE
  COMPLETE: "USER_TASK_COMPLETE",
  COMPLETE_SUCESSS: "USER_TASK_COMPLETE_SUCESSS",
  COMPLETE_ERROR: "USER_TASK_COMPLETE_SUCESSS_ERROR",
  UPDATE_NOTIFICATION: "UPDATE_NOTIFICATION",
  UPDATE_NOTIFICATION_SUCCESS: "UPDATE_NOTIFICATION_SUCCESS",
  UPDATE_NOTIFICATION_ERROR: "UPDATE_NOTIFICATION_ERROR",
  //CLAIM
  CLAIM: "USER_TASK_CLAIM",
  CLAIM_SUCESSS: "USER_TASK_CLAIM_SUCESSS",
  CLAIM_ERROR: "USER_TASK_CLAIM_ERROR",
  //UNCLAIM
  UNCLAIM: "USER_TASK_UNCLAIM",
  UNCLAIM_SUCESSS: "USER_TASK_UNCLAIM_SUCESSS",
  UNCLAIM_ERROR: "USER_TASK_UNCLAIM",
  //ASSIGNE_TO
  ASSIGNE_TO: "USER_TASK_ASSIGNE_TO",
  ASSIGNE_TO_SUCESSS: "USER_TASK_ASSIGNE_TO_SUCESSS",
  ASSIGNE_TO_ERROR: "USER_TASK_ASSIGNE_TO",
};

const PROFILE_STATUS = {
  RESET: "RESET",
};

export { USER_TASK, PROFILE_STATUS };
