const WORKFLOW = {
  RESET: 'WORKFLOW_RESET',
  WORKFLOW_LOADING: 'WORKFLOW_LOADING',

  //USER TASK LIST
  REQUEST_START_WORKFLOW_BY_KEY: 'REQUEST_START_WORKFLOW_BY_KEY',
  RESPONSE_START_WORKFLOW: 'RESPONSE_START_WORKFLOW',
  ERROR_START_WORKFLOW: 'ERROR_START_WORKFLOW',
  START_API: 'START_API',
  END_API: 'END_API',
};

export default WORKFLOW;
