export const APP_TEMPLATES_REQUEST = 'APP_TEMPLATES_REQUEST';
export const APP_TEMPLATE_FORM_REQUEST = 'APP_TEMPLATE_FORM_REQUEST';
export const APP_TEMPLATE_REQUEST_SUCCESS = 'APP_TEMPLATE_REQUEST_SUCCESS';
export const APP_TEMPLATES_REQUEST_SUCCESS = 'APP_TEMPLATES_REQUEST_SUCCESS';
export const APP_TEMPLATE_FORM_REQUEST_SUCCESS = 'APP_TEMPLATE_FORM_REQUEST_SUCCESS';
