const NOTIFICATION = {
  NOTIFICATION_REQUEST: "NOTIFICATION_REQUEST",
  NOTIFICATIONS_REQUEST: "NOTIFICATIONS_REQUEST",
  NOTIFICATION_ID_REQUEST_SUCCESS: "NOTIFICATION_ID_REQUEST_SUCCESS",
  NOTIFICATION_REQUEST_SUCCESS: "NOTIFICATION_REQUEST_SUCCESS",
  NOTIFICATIONS_REQUEST_SUCCESS: "NOTIFICATIONS_REQUEST_SUCCESS",
  NOTIFICATIONS_CLEAN_REQUEST: "NOTIFICATIONS_CLEAN_REQUEST",
  NOTIFICATION_REQUEST_ERROR: "NOTIFICATION_REQUEST_ERROR",
  NOTIFICATION_REQUEST_BY_ID: "NOTIFICATION_REQUEST_BY_ID",
  USER_NOTIFICATIONS: "USER_NOTIFICATIONS",
};

export default NOTIFICATION;
