const USER = {
  USER_REQUEST_BY_ID: 'USER_REQUEST_BY_ID',
  USER_REQUEST_BY_USERNAME: 'USER_REQUEST_BY_USERNAME',
  USER_DEFAULT_PROFILE_REQUEST: 'USER_DEFAULT_PROFILE_REQUEST',

  USER_REQUEST_SUCCESS: 'USER_REQUEST_SUCCESS',
  USER_REQUEST_ERROR: 'USER_REQUEST_ERROR',

  USER_DEFAULT_PROFILE_REQUEST_SUCCESS: 'USER_DEFAULT_PROFILE_REQUEST_SUCCESS',
  USER_DEFAULT_PROFILE_REQUEST_ERROR: 'USER_DEFAULT_PROFILE_REQUEST_ERROR',

  USERS_REQUEST: 'USERS_REQUEST',
  USERS_REQUEST_SUCCESS: 'USERS_REQUEST_SUCCESS',
  USER_SET_SUCCESS: 'USER_SET_SUCCESS',
  USERS_CLEAN_REQUEST: 'USERS_CLEAN_REQUEST'
};

export default USER;
