const CUSTOMER = {
  CHANGE_CUSTOMER: 'customer/CHANGE_CUSTOMER',
  CUSTOMERS_REQUEST: 'CUSTOMERS_REQUEST',
  CUSTOMER_REQUEST_BY_ID: 'CUSTOMER_REQUEST_BY_ID',
  CUSTOMER_REQUEST_PROFILE_BY_ID: 'CUSTOMER_REQUEST_PROFILE_BY_ID',
  CUSTOMER_REQUEST_SUCCESS: 'CUSTOMER_REQUEST_SUCCESS',
  CUSTOMER_REQUEST_ERROR: 'CUSTOMER_REQUEST_ERROR',
  CUSTOMERS_REQUEST_SUCCESS: 'CUSTOMERS_REQUEST_SUCCESS',
  CUSTOMERS_CLEAN_REQUEST: 'CUSTOMERS_CLEAN_REQUEST',
  CUSTOMER_SAVE_REQUEST: 'CUSTOMER_SAVE_REQUEST',
  PROFILE_SAVE_REQUEST: 'PROFILE_SAVE_REQUEST',
  ASSIGNEES_REQUEST_SUCCESS: 'ASSIGNEES_REQUEST_SUCCESS',
};

export default CUSTOMER;
