const USER = {
  LOGGED_USER_REQUEST: "LOGGEDIN_USER_REQUEST",
  LOGGED_USER_REQUEST_SUCCESS: "LOGGEDIN_USER_REQUEST_SUCCESS",
  LOGGED_USER_PROFILE_REQUEST_SUCCESS: "LOGGED_USER_PROFILE_REQUEST_SUCCESS",
  LOGGED_USER_REQUEST_FAILURE: "LOGGEDIN_USER_REQUEST_FAILURE",

  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_ROLES: "USER_ROLES",
  USER_LOADING: "USER_LOADING",

  SET_USER_PROFILE: "SET_USER_PROFILE",

  PROFILE_SET_EDITABLE: "PROFILE_SET_EDITABLE",
  PROFILE_DISABLE_EDITABLE: "PROFILE_DISABLE_EDITABLE",

  PROFILE_REMOVE: "PROFILE_REMOVE",
  PROFILE_SET: "PROFILE_SET",
  PROFILE_CHANGE_RESET: "PROFILE_CHANGE_RESET",

  USERS_REQUEST: "USERS_REQUEST",
  USERS_REQUEST_SUCCESS: "USERS_REQUEST_SUCCESS",

  USER_TASKS: "USER_TASKS",

  USER_LINKS: "USER_LINKS",
};

export { USER };
