const CUSTOMER_DOCUMENTUPLOAD = {
  RESET: 'CUSTOMER_DOCUMENTUPLOAD_RESET',
  //COMPLETE
  COMPLETE: 'CUSTOMER_DOCUMENTUPLOAD_COMPLETE',
  COMPLETE_SUCESSS: 'CUSTOMER_DOCUMENTUPLOAD_COMPLETE_SUCESSS',
  COMPLETE_ERROR: 'CUSTOMER_DOCUMENTUPLOAD_COMPLETE_SUCESSS_ERROR',

  //ASSIGNE_TO
  ASSIGNE_TO: 'CUSTOMER_DOCUMENTUPLOAD_ASSIGNE_TO',
  ASSIGNE_TO_SUCESSS: 'CUSTOMER_DOCUMENTUPLOAD_ASSIGNE_TO_SUCESSS',
  ASSIGNE_TO_ERROR: 'CUSTOMER_DOCUMENTUPLOAD_ASSIGNE_TO'
};

export default CUSTOMER_DOCUMENTUPLOAD;
