const SIGNALR_TYPES = {
  USER_TASK_COMPLETE_SUCESSS: 'SR_USER_TASK_COMPLETE_SUCESSS',
  RESPONSE_USER_TASKS: 'SR_RESPONSE_USER_TASKS',
  NEW_USER_TASK: 'SR_NEW_USER_TASK',
  UPDATE_USER_TASK: 'SR_UPDATE_USER_TASK',
  NEW_NOTIFICATION: 'SR_NEW_NOTIFICATION',
  APPLICATION_STATUS_UPDATE: 'SR_APPLICATION_STATUS_UPDATE',
  PROFILE_STATUS_UPDATE: 'PROFILE_STATUS_UPDATE',
  SIGNALR_STATUS_UPDATE: 'SR_SIGNALR_STATUS_UPDATE',
};

export default SIGNALR_TYPES;
